<?php

namespace Tests\Unit\Services;

use App\Models\Image;
use App\Models\User;
use App\Repository\ImageRepositoryInterface;
use App\Services\ImageService;
use Database\Factories\UserFactory;
use PHPUnit\Framework\TestCase;

class ImageServiceTest extends TestCase
{

//    private $service;
//
//    public function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->service = new ImageService();
//    }


//    public function testImagesUser()
//    {
////        $mock = $this->mock(ImageService::class, function (ImageRepositoryInterface $image) {
////            $image->shouldReceive('process')->once();
////        });
//        $user = User::factory()->create();
//        dd(0);
//        $result=ImageService::class->imagesUser($user->id);
//        dd($result);
//        $this->assertTrue(true);
//    }

//    public function testImageUpload()
//    {
//        $images = factory(Image::class)->create();
//        $this->service->imagesUser();
//        $this->assertTrue(true);
//    }

}
